STATE_INITIAL = "STATE_INIT"
STATE_0 = "STATE_0"
STATE_1 = "STATE_1"
STATE_2 = "STATE_2"
STATE_3 = "STATE_3"
STATE_4 = "STATE_4"
STATE_5 = "STATE_5"
STATE_6 = "STATE_6"
STATE_7 = "STATE_7"
STATE_8 = "STATE_8"
STATE_9 = "STATE_9"
STATE_FINAL = "STATE_FINAL"

SYMBOL_BLANK = "_"
SYMBOL_0 = "0"
SYMBOL_1 = "1"
SYMBOL_2 = "2"
SYMBOL_3 = "3"
SYMBOL_4 = "4"
SYMBOL_5 = "5"
SYMBOL_6 = "6"
SYMBOL_7 = "7"
SYMBOL_8 = "8"
SYMBOL_9 = "9"

MOVE_HEAD_LEFT = "L"
MOVE_HEAD_RIGHT = "R"
MOVE_HEAD_NONE = "N"

MOVE_HEAD_DIRECTIONS = {
    MOVE_HEAD_LEFT: "Left",
    MOVE_HEAD_RIGHT: "Right",
    MOVE_HEAD_NONE: "None",
}

SYMBOLS = {
    SYMBOL_0,
    SYMBOL_1,
    SYMBOL_2,
    SYMBOL_3,
    SYMBOL_4,
    SYMBOL_5,
    SYMBOL_6,
    SYMBOL_7,
    SYMBOL_8,
    SYMBOL_9,
}
